// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export class SliceGetter {
    

    get ffiValue(): pointer;

    static getSlice(): Array<number>;
}